"use client";

/**
 * Internal home for design mockups that need to be reviewed before they ship.
 *
 * First tenant: the Autoremote partnership, drafted for the 1 September launch.
 * The meeting notes with Autoremote say the in-app presentation is produced as
 * a draft and published only after a joint review, so this page exists to make
 * the draft reviewable without putting it in front of a customer.
 */

import { useState } from "react";

/**
 * The deployed clickable mockup. Override with NEXT_PUBLIC_MOCKUP_URL if it
 * ever moves.
 *
 * It sits behind Vercel Authentication on purpose. The fixtures behind it are
 * recorded InfoPro and HaynesPro technical data, which is licensed, so the
 * mockup must not be reachable by an open URL. Anyone who needs to see it needs
 * access to the Vercel team, or a screen share.
 */
const LIVE_URL =
  process.env.NEXT_PUBLIC_MOCKUP_URL ?? "https://wrenchlane-autoremote-mockup.vercel.app";
const PLAN_URL = "https://claude.ai/code/artifact/73816390-771e-4ba0-a6c5-30c210139ef8";

interface Shot {
  file: string;
  title: string;
  caption: string;
}

const SHOTS: Shot[] = [
  {
    file: "ar-hero.jpg",
    title: "The trigger, on a real case",
    caption:
      "A Mercedes GL X164 whose EGR valve was replaced and which is still in limp mode. The 90% cause, generated by WrenchLane in production, is “Incomplete EGR System Adaptation”, needing a teach-in on an OEM-level tool. The block names the phrase that triggered it, so it reads as a diagnosis rather than an advert.",
  },
  {
    file: "ar-quiet.jpg",
    title: "And when it stays quiet",
    caption:
      "The same feature on a VW Touareg intake leak. Nothing about that diagnosis needs programming, so nothing is offered. Two of five causes trigger on the Mercedes, three do not. The restraint is what makes the offer credible.",
  },
  {
    file: "ar-1-gate.jpg",
    title: "Asked once",
    caption:
      "The step the sketch never had, and the thing the meeting notes actually agreed. Answered once per workshop, then never again. The SERMI question is an addition, because Autoremote state on their own site that they can only serve certified workshops.",
  },
  {
    file: "ar-2-form.jpg",
    title: "The referral",
    caption:
      "Autoremote’s own six fields, pre filled, plus the vehicle, all five fault codes and the job. Their public order form captures none of that. Send stays disabled until consent is ticked.",
  },
  {
    file: "ar-3-sent.jpg",
    title: "Handed over",
    caption:
      "Autoremote takes over onboarding, hardware, delivery and the invoice. WrenchLane’s job ends here, which is exactly the affiliate boundary the notes drew.",
  },
  {
    file: "ar-5-handoff.jpg",
    title: "Existing customers",
    caption:
      "Autoremote or Launch, then sent onward with the job details. From the second time on the questions are skipped and the button goes straight here.",
  },
  {
    file: "ar-pricing.jpg",
    title: "Pricing, deliberately not a plan",
    caption:
      "A partner strip that sells nothing, shaped like the data-partner strip below it. This replaces the sketch’s “Premium + Autoremote” tier. See the three flags below for why.",
  },
];

const FLAGS = [
  {
    title: "The bundled subscription contradicts the affiliate model",
    body: "The sketch sells Premium + Autoremote at 1 195 kr per mechanic per month, billed with the WrenchLane subscription. The notes say three separate times that Autoremote owns the customer relationship, their terms apply, and WrenchLane “ska inte vara säljande eller levererande part”.",
  },
  {
    title: "The maths does not work either",
    body: "Autoremote does not sell subscriptions. Their published prices are per job, ex VAT, invoiced after the work, explicitly with no tokens or prepayment: 600 kr standard, 1 595 kr avancerad, 640 kr batteri. The sketch’s 595 kr monthly add-on includes component programming, which costs 1 595 kr a job.",
  },
  {
    title: "It prices per seat",
    body: "Every tier in the sketch is per mekaniker. That is the pricing shape we have moved away from.",
  },
];

const QUESTIONS = [
  "Where exactly do existing customers get sent? Autoremote publicly have one generic enquiry page and a phone number.",
  "What does “Launch” route to? Launch is a diagnostic tablet brand distributed by KGK in Sweden.",
  "How does Autoremote know a lead came from us? There is no affiliate mechanic described anywhere yet.",
  "Who receives the referral emails, and how fast do they answer?",
  "Do we pre qualify on SERMI in the app, or let Autoremote do it?",
  "Consent and terms: we would be passing workshop contact details to a third party.",
];

export function MockupClient() {
  const [open, setOpen] = useState<Shot | null>(null);

  return (
    <div className="mx-auto max-w-5xl px-6 py-8">
      <header className="mb-6">
        <h1 className="text-2xl font-semibold text-slate-900">Mockup</h1>
        <p className="mt-1 text-slate-600">
          Autoremote in WrenchLane, drafted for the 1 September launch.
        </p>
      </header>

      <div className="mb-8 rounded-lg border border-amber-300 bg-amber-50 p-4">
        <p className="text-sm font-medium text-amber-900">
          Draft. Not published, and not live in the product.
        </p>
        <p className="mt-1 text-sm text-amber-800">
          Everything below is the real production app running against recorded, anonymised
          production data, with the Autoremote work added behind a feature flag. The meeting
          notes say the in-app presentation is published only after a joint review with
          Autoremote.
        </p>
      </div>

      <div className="mb-10 flex flex-wrap gap-3">
        {LIVE_URL ? (
          <a
            href={LIVE_URL}
            target="_blank"
            rel="noopener noreferrer"
            className="rounded-md bg-slate-900 px-4 py-2 text-sm font-medium text-white hover:bg-slate-800"
          >
            Open the clickable mockup
          </a>
        ) : (
          <span className="rounded-md border border-dashed border-slate-300 px-4 py-2 text-sm text-slate-500">
            Clickable mockup not deployed yet. Set NEXT_PUBLIC_MOCKUP_URL to link it here.
          </span>
        )}
        <a
          href={PLAN_URL}
          target="_blank"
          rel="noopener noreferrer"
          className="rounded-md border border-slate-300 bg-white px-4 py-2 text-sm font-medium text-slate-700 hover:bg-slate-50"
        >
          Open the full plan
        </a>
      </div>

      <p className="-mt-6 mb-10 text-sm text-slate-500">
        The clickable mockup is behind Vercel Authentication, so opening it needs access to
        the Vercel team. That is deliberate: the data behind it is recorded InfoPro and
        HaynesPro technical content, which is licensed and must not sit on an open URL. The
        screens below are here so the draft can be reviewed without that.
      </p>

      <section className="mb-12">
        <h2 className="mb-1 text-lg font-semibold text-slate-900">The screens</h2>
        <p className="mb-5 text-sm text-slate-600">
          Click any screen to enlarge. These are captures of the running mockup, not drawings.
        </p>
        <div className="grid grid-cols-1 gap-6 sm:grid-cols-2">
          {SHOTS.map((shot) => (
            <figure key={shot.file} className="overflow-hidden rounded-lg border border-slate-200 bg-white">
              <button
                type="button"
                onClick={() => setOpen(shot)}
                className="block w-full cursor-zoom-in"
                aria-label={`Enlarge: ${shot.title}`}
              >
                {/* Plain img: these are static local captures, and next/image
                    buys nothing for an internal review page. */}
                {/* eslint-disable-next-line @next/next/no-img-element */}
                <img
                  src={`/mockup/${shot.file}`}
                  alt={shot.title}
                  className="w-full border-b border-slate-200"
                  loading="lazy"
                />
              </button>
              <figcaption className="p-4">
                <p className="text-sm font-semibold text-slate-900">{shot.title}</p>
                <p className="mt-1 text-sm leading-relaxed text-slate-600">{shot.caption}</p>
              </figcaption>
            </figure>
          ))}
        </div>
      </section>

      <section className="mb-12">
        <h2 className="mb-1 text-lg font-semibold text-slate-900">
          Where the sketch and the agreement pull apart
        </h2>
        <p className="mb-5 text-sm text-slate-600">
          Worth settling before anything is shown to Autoremote.
        </p>
        <div className="space-y-4">
          {FLAGS.map((flag) => (
            <div key={flag.title} className="rounded-lg border border-slate-200 bg-white p-4">
              <p className="text-sm font-semibold text-slate-900">{flag.title}</p>
              <p className="mt-1 text-sm leading-relaxed text-slate-600">{flag.body}</p>
            </div>
          ))}
        </div>
      </section>

      <section className="mb-12">
        <h2 className="mb-4 text-lg font-semibold text-slate-900">Open questions</h2>
        <ul className="space-y-2">
          {QUESTIONS.map((q) => (
            <li key={q} className="flex gap-3 text-sm leading-relaxed text-slate-600">
              <span aria-hidden className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-slate-400" />
              <span>{q}</span>
            </li>
          ))}
        </ul>
      </section>

      <section>
        <h2 className="mb-2 text-lg font-semibold text-slate-900">Running it locally</h2>
        <p className="mb-3 text-sm text-slate-600">
          The mockup is the production frontend on branch <code className="rounded bg-slate-100 px-1 py-0.5 text-xs">autoremote-mock</code>, running in mock mode so it needs no AWS, Stripe or backend credentials.
        </p>
        <pre className="overflow-x-auto rounded-lg bg-slate-900 p-4 text-xs leading-relaxed text-slate-100">
{`cd ~/wrenchlane-design-mock/.claude/worktrees/design-mock
node node_modules/next/dist/bin/next dev --turbo --port 3030
# then open
# http://localhost:3030/sv/start/vehicle/diagnostic/5cd52b75-3f32-4c85-b8fc-cdfd40c62aa7`}
        </pre>
      </section>

      {open && (
        <div
          className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/80 p-6"
          onClick={() => setOpen(null)}
          role="dialog"
          aria-modal="true"
          aria-label={open.title}
        >
          <div className="max-h-full max-w-6xl overflow-auto" onClick={(e) => e.stopPropagation()}>
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img src={`/mockup/${open.file}`} alt={open.title} className="w-full rounded-lg" />
            <p className="mt-3 text-sm text-slate-200">{open.caption}</p>
          </div>
          <button
            type="button"
            onClick={() => setOpen(null)}
            className="absolute right-6 top-6 rounded-md bg-white/10 px-3 py-1.5 text-sm text-white hover:bg-white/20"
          >
            Close
          </button>
        </div>
      )}
    </div>
  );
}
