/**
 * Remove keywords that can never match a search.
 *
 *   npx tsx --env-file=<env> scripts/prune-impossible-keywords.mts [--apply] [--max-ops N]
 *
 * Dry run by default.
 *
 * QUOTA IS THE BINDING CONSTRAINT, NOT CORRECTNESS
 *
 * The developer token has Explorer access, which allows 2,880 operations a day
 * against production. There are far more removals than that, and a validate-only
 * pass costs quota just like a real one, so validating the whole set before
 * writing any of it burns a day's budget and removes nothing.
 *
 * So: validate one batch as a shape check, then apply in batches under a daily
 * budget, and stop cleanly when the quota is gone. The script is naturally
 * resumable because it re-reads the account every run and only ever proposes
 * what is still there, so running it again tomorrow continues from where it
 * stopped without any bookkeeping.
 *
 * WHAT IT REMOVES, AND ON WHAT EVIDENCE
 *
 * A keyword goes only if all three hold: every code-shaped token in it has an
 * impossible second character under SAE J2012, it does not name a marque (so
 * the token is not a truck model like C4500), and it has never served a single
 * impression in the account's lifetime. The last one is evidence rather than
 * inference and it overrules the other two.
 *
 * The `error codes` campaign is the reason this exists. It holds 26,196
 * keywords and exactly one has ever served an impression, because most of it
 * was generated by enumerating P plus four digits rather than by choosing
 * codes that exist.
 *
 * It never touches anything in an ENABLED campaign, whatever the shape of the
 * keyword. Nothing here is worth a surprise in a campaign that is spending.
 */

import {
  createGoogleAdsAccess,
  googleAdsRequest,
  googleAdsSearch,
  hasGoogleAdsApiCredentials,
} from "@/lib/ceo/sync/google-ads-client";
import { judgeKeyword } from "@/lib/landing/keyword-audit";

const apply = process.argv.includes("--apply");

if (!hasGoogleAdsApiCredentials()) {
  console.error("Google Ads API is not configured.");
  process.exit(1);
}

const access = await createGoogleAdsAccess();

type CriterionRow = {
  campaign?: { name?: string; status?: string };
  adGroupCriterion?: {
    resourceName?: string;
    keyword?: { text?: string };
  };
};
type MetricRow = {
  adGroupCriterion?: { keyword?: { text?: string } };
  metrics?: { impressions?: string };
};

const [criteria, metrics] = await Promise.all([
  googleAdsSearch<CriterionRow>(
    access,
    `SELECT campaign.name, campaign.status, ad_group_criterion.resource_name,
            ad_group_criterion.keyword.text
     FROM ad_group_criterion
     WHERE ad_group_criterion.type = 'KEYWORD'
       AND ad_group_criterion.status != 'REMOVED'`,
  ),
  googleAdsSearch<MetricRow>(
    access,
    `SELECT ad_group_criterion.keyword.text, metrics.impressions
     FROM keyword_view
     WHERE segments.date BETWEEN '2020-01-01' AND '2026-12-31'`,
  ),
]);

const impressions = new Map<string, number>();
for (const row of metrics) {
  const text = row.adGroupCriterion?.keyword?.text;
  if (!text) continue;
  impressions.set(
    text,
    (impressions.get(text) ?? 0) + Number(row.metrics?.impressions ?? 0),
  );
}

const removable: { resourceName: string; text: string; campaign: string }[] = [];
const kept = new Map<string, number>();
let inEnabled = 0;

for (const row of criteria) {
  const text = row.adGroupCriterion?.keyword?.text;
  const resourceName = row.adGroupCriterion?.resourceName;
  const campaign = row.campaign?.name ?? "(unknown)";
  if (!text || !resourceName) continue;

  const verdict = judgeKeyword(text, impressions.get(text) ?? 0);
  if (!verdict.removable) {
    kept.set(verdict.reason, (kept.get(verdict.reason) ?? 0) + 1);
    continue;
  }
  // Never touch a campaign that is running, whatever the keyword looks like.
  if (row.campaign?.status === "ENABLED") {
    inEnabled += 1;
    continue;
  }
  removable.push({ resourceName, text, campaign });
}

const byCampaign = new Map<string, number>();
for (const row of removable) {
  byCampaign.set(row.campaign, (byCampaign.get(row.campaign) ?? 0) + 1);
}

console.log(`Keywords examined       : ${criteria.length}`);
console.log(`Removable               : ${removable.length}`);
for (const [campaign, count] of [...byCampaign].sort((a, b) => b[1] - a[1])) {
  console.log(`   ${campaign.padEnd(24)} ${count}`);
}
console.log(`Skipped, campaign ENABLED: ${inEnabled}`);
console.log("Kept, by reason:");
for (const [reason, count] of [...kept].sort((a, b) => b[1] - a[1])) {
  console.log(`   ${String(count).padStart(6)}  ${reason}`);
}
console.log("");
console.log(`Sample: ${removable.slice(0, 8).map((r) => r.text).join(", ")}`);

if (!apply) {
  console.log("");
  console.log("DRY RUN. Nothing removed. Pass --apply to write.");
  process.exit(0);
}

/**
 * One batch is validated as a shape check, then the rest are applied directly.
 *
 * Validating everything first would double the quota cost of a run that is
 * already quota-bound, and the failure mode it protects against, a malformed
 * resource name, is identical across every operation in the set.
 */
const operations = removable.map((row) => ({ remove: row.resourceName }));
const budget = Number(
  process.argv[process.argv.indexOf("--max-ops") + 1] || 2500,
);
const planned = operations.slice(0, budget);

console.log("");
console.log(
  `Explorer quota is 2,880 operations a day. Removing up to ${planned.length} this run; ${operations.length - planned.length} would remain for a later run.`,
);

const BATCH = 500;

try {
  await googleAdsRequest(
    access,
    `customers/${access.customerId}/adGroupCriteria:mutate`,
    {
      operations: planned.slice(0, BATCH),
      partialFailure: false,
      validateOnly: true,
    },
  );
  console.log("Shape check passed. Applying.");
} catch (err) {
  console.error(`Shape check failed, nothing written: ${String(err)}`);
  process.exit(1);
}

let done = 0;
for (let i = 0; i < planned.length; i += BATCH) {
  const batch = planned.slice(i, i + BATCH);
  try {
    await googleAdsRequest(
      access,
      `customers/${access.customerId}/adGroupCriteria:mutate`,
      { operations: batch, partialFailure: false },
    );
  } catch (err) {
    const message = String(err);
    if (message.includes("RESOURCE_EXHAUSTED")) {
      console.log("");
      console.log(
        `Daily quota reached after ${done} removals. Re-run tomorrow to continue; the script picks up where it stopped because it re-reads the account each time.`,
      );
      process.exit(0);
    }
    throw err;
  }
  done += batch.length;
  console.log(`  removed ${done}/${planned.length}`);
}
console.log("");
console.log(`Done. ${done} keywords removed this run.`);
if (operations.length > done) {
  console.log(`${operations.length - done} still to go. Re-run to continue.`);
}
