/**
 * Upload the plan-page ad creatives into the Google Ads account as image assets.
 *
 *   npx tsx --env-file=.env.local scripts/upload-plan-creatives.mts           # list
 *   npx tsx --env-file=.env.local scripts/upload-plan-creatives.mts --apply
 *
 * Uploading an asset has no serving effect on its own. An image only starts
 * showing once it is linked into an asset group, which is a separate and much
 * bigger decision, so this script deliberately stops at upload.
 *
 * Why these images exist at all: the account holds 130 image assets and 14
 * YouTube videos, and not one of them names a plan, states a price, or shows
 * the vehicle meter. The video library is entirely fault-code demos (P0300,
 * P0171), which suits the fault-code pages and says nothing about a page whose
 * argument is 50 vehicles a month with unlimited mechanics.
 *
 * Source images are generated by _planning/google-ads/creatives/generate.py,
 * which composes real product screenshots pulled from the live plan pages with
 * a minimal text overlay. Text is kept short on purpose: Google supplies the
 * headline, so an image crowded with copy competes with its own ad.
 *
 * Naming matters. Assets are named wl-<plan>-<concept>-<ratio>-<WxH> so the
 * asset list in the Google Ads UI stays readable, and so a re-run can tell
 * which images are already uploaded instead of creating duplicates.
 */

import { readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";
import {
  createGoogleAdsAccess,
  googleAdsRequest,
  googleAdsSearch,
  hasGoogleAdsApiCredentials,
} from "@/lib/ceo/sync/google-ads-client";

const APPLY = process.argv.includes("--apply");
const DIR =
  process.argv.find((a) => a.startsWith("--dir="))?.slice("--dir=".length) ??
  join(process.cwd(), "_planning/google-ads/creatives");

/** Google's asset minimums, so a mis-sized render is caught before upload. */
const ALLOWED = new Set(["1200x628", "1200x1200", "960x1200"]);

if (!hasGoogleAdsApiCredentials()) {
  console.error(
    "Google Ads API is not configured: need GOOGLE_ADS_DEVELOPER_TOKEN and GOOGLE_ADS_CUSTOMER_ID.",
  );
  process.exit(1);
}

const files = readdirSync(DIR)
  .filter((f) => f.startsWith("wl-") && f.endsWith(".png"))
  .sort();

if (files.length === 0) {
  console.error(
    `No creatives found in ${DIR}.\n` +
      "Generate them first: python3 _planning/google-ads/creatives/generate.py",
  );
  process.exit(1);
}

const access = await createGoogleAdsAccess();

// Read existing asset names so a re-run uploads only what is missing. Explorer
// quota is tight and a duplicate upload spends it for nothing.
const existing = await googleAdsSearch<{ asset: { name?: string } }>(
  access,
  "SELECT asset.id, asset.name FROM asset WHERE asset.type = 'IMAGE'",
);
const have = new Set(
  existing.map((r) => r.asset.name).filter((n): n is string => Boolean(n)),
);

type Pending = { name: string; file: string; bytes: Buffer };
const pending: Pending[] = [];
let skipped = 0;

for (const file of files) {
  const name = file.replace(/\.png$/, "");
  const dims = name.match(/(\d+x\d+)$/)?.[1];
  if (!dims || !ALLOWED.has(dims)) {
    console.error(`  ! ${file}: ${dims ?? "no"} is not a Google asset size`);
    process.exit(1);
  }
  if (have.has(name)) {
    skipped += 1;
    continue;
  }
  pending.push({ name, file, bytes: readFileSync(join(DIR, file)) });
}

console.log(`Customer ${access.customerId}. Mode: ${APPLY ? "APPLY" : "LIST"}.`);
console.log(`${files.length} creatives on disk, ${skipped} already uploaded.`);

if (pending.length === 0) {
  console.log("Nothing to upload.");
  process.exit(0);
}

for (const p of pending) {
  console.log(`  ${p.name}  ${(p.bytes.length / 1024).toFixed(0)} KB`);
}

if (!APPLY) {
  console.log("\nDry run. Re-run with --apply to upload.");
  process.exit(0);
}

// One operation per asset, in small batches. Uploads carry image bytes, so a
// batch that is too large risks a request-size failure on top of quota.
const BATCH = 6;
let sent = 0;
for (let i = 0; i < pending.length; i += BATCH) {
  const chunk = pending.slice(i, i + BATCH);
  const ops = chunk.map((p) => ({
    assetOperation: {
      create: {
        name: p.name,
        type: "IMAGE",
        imageAsset: { data: p.bytes.toString("base64") },
      },
    },
  }));
  try {
    await googleAdsRequest(
      access,
      `customers/${access.customerId}/googleAds:mutate`,
      { mutateOperations: ops },
    );
    sent += chunk.length;
    console.log(`  uploaded ${sent}/${pending.length}`);
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    if (message.includes("RESOURCE_EXHAUSTED")) {
      console.log(
        `\nQuota reached after ${sent} of ${pending.length}. ` +
          "Re-run to resume; already-uploaded images are skipped by name.",
      );
      process.exit(0);
    }
    console.error(`\nFAILED after ${sent}: ${message}`);
    process.exit(1);
  }
}

console.log(`\nUploaded ${sent} image assets.`);
console.log(
  "These are not serving yet. Linking them into a Performance Max asset group\n" +
    "per plan is the next step, and it changes where live traffic lands, so it\n" +
    "is a deliberate decision rather than a side effect of uploading.",
);
