-- Inbox draft-reply cache.
--
-- When a non-English reply lands, the inbox auto-suggests an English draft via
-- Claude. We cache the draft on the inbox_messages row so re-opening the
-- thread is instant (and free). The user can click "Regenerate" to clear and
-- refetch.

ALTER TABLE inbox_messages
  ADD COLUMN IF NOT EXISTS draft_en TEXT,
  ADD COLUMN IF NOT EXISTS draft_generated_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS draft_model TEXT;

COMMENT ON COLUMN inbox_messages.draft_en IS 'Suggested English reply to this incoming message, generated by Claude. User edits + approves before send. NULL = not yet generated.';
COMMENT ON COLUMN inbox_messages.draft_generated_at IS 'When the cached draft was produced. Used for cache-busting if we ever invalidate.';
COMMENT ON COLUMN inbox_messages.draft_model IS 'Model used to generate the cached draft (audit trail).';
